name: Daily Sync

on:
  schedule:
    - cron: '0 2 * * *'  # 8 AM IST (which is 2:00 UTC)
  workflow_dispatch:     # optional, lets you manually trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run final.js
        run: node final.js
